import type { BlockCategory, BlockDefinition } from "./types";

// Special start block — not shown in palette, auto-placed per level
export const TRAFFIC_SOURCE_BLOCK: BlockDefinition = {
  type: "traffic-source",
  label: "Users",
  name: "Traffic",
  category: "networking",
  description: "Incoming user traffic — the entry point for all requests",
  icon: "Users",
  costPerMonth: 0,
  ports: [{ id: "http-out-0", protocol: "HTTP", direction: "out" }],
  maxRps: Infinity,
  maxConnections: Infinity,
  baseLatencyMs: 0,
  routingStrategy: "passthrough",
  scaling: "managed",
};

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  // --- Networking ---
  {
    type: "dns",
    label: "DNS",
    name: "Route 53",
    category: "networking",
    description: "Domain name resolution — entry point for all traffic",
    icon: "Globe",
    costPerMonth: 5,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 80000,
    maxConnections: 160000,
    baseLatencyMs: 1,
    routingStrategy: "passthrough",
    scaling: "managed",
    edgeLatencyReduction: 5,
    attackAbsorbRate: 0.15,
    // Pareto-tuned: each provider wins on one axis, loses on another.
    //   Cloudflare DNS — best shave + free, capacity-capped at 40k
    //   Route 53       — best DDoS absorb, premium price
    //   Cloud DNS      — budget mid, mediocre everywhere
    //   Azure DNS      — highest capacity, weakest edge/absorb
    providers: [
      {
        provider: "Route 53",
        costPerMonth: 5,
        maxRps: 80000,
        maxConnections: 160000,
        baseLatencyMs: 1,
        edgeLatencyReduction: 6,
        attackAbsorbRate: 0.35,
      },
      {
        provider: "Cloudflare DNS",
        costPerMonth: 0,
        maxRps: 40000,
        maxConnections: 80000,
        baseLatencyMs: 1,
        edgeLatencyReduction: 12,
        attackAbsorbRate: 0.2,
      },
      {
        provider: "Cloud DNS",
        costPerMonth: 3,
        maxRps: 60000,
        maxConnections: 120000,
        baseLatencyMs: 2,
        edgeLatencyReduction: 5,
        attackAbsorbRate: 0.15,
      },
      {
        provider: "Azure DNS",
        costPerMonth: 8,
        maxRps: 150000,
        maxConnections: 300000,
        baseLatencyMs: 1,
        edgeLatencyReduction: 3,
        attackAbsorbRate: 0.1,
      },
    ],
  },
  {
    type: "cdn",
    label: "CDN",
    name: "CloudFront",
    category: "networking",
    description: "Content delivery network — caches static assets at edge",
    icon: "Zap",
    costPerMonth: 50,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 120000,
    maxConnections: 240000,
    baseLatencyMs: 5,
    routingStrategy: "passthrough",
    hitRate: 0.85,
    scaling: "managed",
    // Pareto-tuned: each provider wins on one axis, loses on another.
    //   Cloudflare — cheapest + fastest edge, low hit-rate, capacity-capped
    //   CloudFront — best hit-rate, premium price
    //   Cloud CDN  — budget mid, lowest hit-rate
    //   Azure CDN  — highest capacity, mid hit-rate, slowest of the premium tier
    providers: [
      {
        provider: "CloudFront",
        costPerMonth: 50,
        maxRps: 100000,
        maxConnections: 200000,
        baseLatencyMs: 5,
        hitRate: 0.9,
      },
      {
        provider: "Cloud CDN",
        costPerMonth: 35,
        maxRps: 90000,
        maxConnections: 180000,
        baseLatencyMs: 6,
        hitRate: 0.78,
      },
      {
        provider: "Azure CDN",
        costPerMonth: 55,
        maxRps: 180000,
        maxConnections: 360000,
        baseLatencyMs: 5,
        hitRate: 0.85,
      },
      {
        provider: "Cloudflare",
        costPerMonth: 20,
        maxRps: 60000,
        maxConnections: 120000,
        baseLatencyMs: 3,
        hitRate: 0.82,
      },
    ],
  },
  {
    type: "load-balancer",
    label: "Load Balancer",
    name: "Nginx",
    category: "networking",
    description: "Distributes traffic across multiple servers",
    icon: "GitBranch",
    costPerMonth: 25,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      {
        id: "http-out-0",
        protocol: "HTTP",
        direction: "out",
        label: "Backends",
      },
    ],
    maxRps: 200000,
    maxConnections: 400000,
    baseLatencyMs: 1,
    routingStrategy: "round-robin",
    scaling: "managed",
    providers: [
      {
        provider: "Nginx",
        costPerMonth: 25,
        maxRps: 200000,
        maxConnections: 400000,
        baseLatencyMs: 1,
      },
      {
        provider: "HAProxy",
        costPerMonth: 20,
        maxRps: 180000,
        maxConnections: 360000,
        baseLatencyMs: 2,
      },
      {
        provider: "AWS ALB",
        costPerMonth: 35,
        maxRps: 250000,
        maxConnections: 500000,
        baseLatencyMs: 2,
      },
      {
        provider: "Traefik",
        costPerMonth: 15,
        maxRps: 120000,
        maxConnections: 240000,
        baseLatencyMs: 1,
      },
    ],
  },
  {
    type: "api-gateway",
    label: "API Gateway",
    name: "Kong",
    category: "networking",
    description: "API management, routing, and throttling",
    icon: "Route",
    costPerMonth: 40,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 150000,
    maxConnections: 300000,
    baseLatencyMs: 5,
    routingStrategy: "passthrough",
    queueLimit: 500,
    scaling: "managed",
    providers: [
      {
        provider: "Kong",
        costPerMonth: 40,
        maxRps: 150000,
        maxConnections: 300000,
        baseLatencyMs: 5,
      },
      {
        provider: "AWS API GW",
        costPerMonth: 50,
        maxRps: 180000,
        maxConnections: 360000,
        baseLatencyMs: 8,
      },
      {
        provider: "Apigee",
        costPerMonth: 60,
        maxRps: 160000,
        maxConnections: 320000,
        baseLatencyMs: 6,
      },
    ],
  },

  // --- Security ---
  {
    type: "firewall",
    label: "Firewall",
    name: "AWS WAF",
    category: "security",
    description: "Filters malicious traffic and enforces security rules",
    icon: "Shield",
    costPerMonth: 20,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 200000,
    maxConnections: 400000,
    baseLatencyMs: 2,
    routingStrategy: "passthrough",
    scaling: "managed",
    providers: [
      {
        provider: "AWS WAF",
        costPerMonth: 20,
        maxRps: 200000,
        maxConnections: 400000,
        baseLatencyMs: 2,
      },
      {
        provider: "Cloudflare WAF",
        costPerMonth: 15,
        maxRps: 180000,
        maxConnections: 360000,
        baseLatencyMs: 1,
      },
      {
        provider: "Azure Firewall",
        costPerMonth: 30,
        maxRps: 220000,
        maxConnections: 440000,
        baseLatencyMs: 2,
      },
    ],
  },
  {
    type: "rate-limiter",
    label: "Rate Limiter",
    name: "Rate Limiter",
    category: "security",
    description: "Throttles excessive requests to prevent abuse",
    icon: "Gauge",
    costPerMonth: 15,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 150000,
    maxConnections: 300000,
    baseLatencyMs: 3,
    routingStrategy: "passthrough",
    scaling: "managed",
  },

  // --- Compute ---
  {
    type: "app-server",
    label: "App Server",
    name: "Node.js",
    category: "compute",
    description: "Runs application logic and business rules",
    icon: "Cpu",
    costPerMonth: 35,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "tcp-in-0", protocol: "TCP", direction: "in" },
      { id: "sql-out-0", protocol: "SQL", direction: "out" },
      { id: "redis-out-0", protocol: "Redis", direction: "out" },
      { id: "amqp-out-0", protocol: "AMQP", direction: "out" },
      { id: "s3-out-0", protocol: "S3", direction: "out" },
    ],
    maxRps: 3500,
    maxConnections: 7000,
    baseLatencyMs: 10,
    routingStrategy: "passthrough",
    queueLimit: 200,
    timeoutMs: 2000,
    scaling: "counter",
    providers: [
      {
        provider: "Node.js",
        costPerMonth: 35,
        maxRps: 3500,
        maxConnections: 7000,
        baseLatencyMs: 10,
      },
      {
        provider: "Go",
        costPerMonth: 55,
        maxRps: 8000,
        maxConnections: 16000,
        baseLatencyMs: 5,
      },
      {
        provider: "Java/Spring",
        costPerMonth: 40,
        maxRps: 5000,
        maxConnections: 10000,
        baseLatencyMs: 14,
      },
      {
        provider: "Python/Django",
        costPerMonth: 25,
        maxRps: 2000,
        maxConnections: 4000,
        baseLatencyMs: 18,
      },
    ],
  },
  {
    type: "websocket-server",
    label: "WebSocket Server",
    name: "Socket.IO",
    category: "compute",
    description: "Holds long-lived bidirectional connections for realtime apps",
    icon: "Radio",
    costPerMonth: 45,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      {
        id: "redis-out-0",
        protocol: "Redis",
        direction: "out",
        label: "Pub/Sub",
      },
      { id: "sql-out-0", protocol: "SQL", direction: "out", label: "History" },
    ],
    maxRps: 5000,
    maxConnections: 50000,
    baseLatencyMs: 8,
    routingStrategy: "passthrough",
    queueLimit: 500,
    timeoutMs: 3000,
    scaling: "counter",
    providers: [
      {
        provider: "Socket.IO",
        costPerMonth: 45,
        maxRps: 5000,
        maxConnections: 50000,
        baseLatencyMs: 8,
      },
      {
        provider: "ws (Node)",
        costPerMonth: 35,
        maxRps: 4000,
        maxConnections: 40000,
        baseLatencyMs: 6,
      },
      {
        provider: "Phoenix",
        costPerMonth: 60,
        maxRps: 8000,
        maxConnections: 100000,
        baseLatencyMs: 4,
      },
      {
        provider: "Pushpin",
        costPerMonth: 50,
        maxRps: 6000,
        maxConnections: 80000,
        baseLatencyMs: 5,
      },
    ],
  },
  // --- Storage ---
  {
    type: "sql-db",
    label: "SQL Database",
    name: "PostgreSQL",
    category: "storage",
    description: "Relational database for structured data",
    icon: "Database",
    costPerMonth: 80,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 2500,
    maxConnections: 500,
    baseLatencyMs: 14,
    routingStrategy: "none",
    queueLimit: 500,
    timeoutMs: 5000,
    scalesReadsOnly: true,
    scaling: "counter",
    providers: [
      {
        provider: "PostgreSQL",
        costPerMonth: 80,
        maxRps: 2500,
        maxConnections: 500,
        baseLatencyMs: 14,
      },
      {
        provider: "MySQL",
        costPerMonth: 65,
        maxRps: 3000,
        maxConnections: 600,
        baseLatencyMs: 18,
      },
      {
        provider: "Aurora",
        costPerMonth: 120,
        maxRps: 6000,
        maxConnections: 1000,
        baseLatencyMs: 8,
      },
      {
        provider: "Cloud SQL",
        costPerMonth: 95,
        maxRps: 4000,
        maxConnections: 700,
        baseLatencyMs: 12,
      },
    ],
  },
  {
    type: "nosql-db",
    label: "NoSQL Database",
    name: "MongoDB",
    category: "storage",
    description: "Document database for flexible schemas",
    icon: "Layers",
    costPerMonth: 60,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 6000,
    maxConnections: 2000,
    baseLatencyMs: 9,
    routingStrategy: "none",
    queueLimit: 1000,
    timeoutMs: 3000,
    scalesReadsOnly: true,
    scaling: "counter",
    providers: [
      {
        provider: "MongoDB",
        costPerMonth: 60,
        maxRps: 6000,
        maxConnections: 2000,
        baseLatencyMs: 9,
      },
      {
        provider: "DynamoDB",
        costPerMonth: 80,
        maxRps: 12000,
        maxConnections: 5000,
        baseLatencyMs: 5,
      },
      {
        provider: "Cassandra",
        costPerMonth: 70,
        maxRps: 15000,
        maxConnections: 3000,
        baseLatencyMs: 10,
      },
      {
        provider: "Firestore",
        costPerMonth: 40,
        maxRps: 3000,
        maxConnections: 1000,
        baseLatencyMs: 14,
      },
    ],
  },
  {
    type: "cache",
    label: "Cache",
    name: "Redis",
    category: "storage",
    description: "In-memory cache for ultra-fast reads",
    icon: "MemoryStick",
    costPerMonth: 35,
    ports: [{ id: "redis-in-0", protocol: "Redis", direction: "in" }],
    maxRps: 35000,
    maxConnections: 10000,
    baseLatencyMs: 1,
    routingStrategy: "none",
    hitRate: 0.8,
    scaling: "counter",
    providers: [
      {
        provider: "Redis",
        costPerMonth: 35,
        maxRps: 35000,
        maxConnections: 10000,
        baseLatencyMs: 1,
      },
      {
        provider: "Memcached",
        costPerMonth: 30,
        maxRps: 30000,
        maxConnections: 15000,
        baseLatencyMs: 1,
      },
      {
        provider: "ElastiCache",
        costPerMonth: 55,
        maxRps: 45000,
        maxConnections: 12000,
        baseLatencyMs: 1,
      },
      {
        provider: "Dragonfly",
        costPerMonth: 45,
        maxRps: 60000,
        maxConnections: 20000,
        baseLatencyMs: 1,
      },
    ],
  },
  {
    type: "object-storage",
    label: "Object Storage",
    name: "S3",
    category: "storage",
    description: "Scalable object storage for files and media",
    icon: "HardDrive",
    costPerMonth: 20,
    ports: [
      {
        id: "http-in-0",
        protocol: "HTTP",
        direction: "in",
        label: "Static origin",
      },
      { id: "s3-in-0", protocol: "S3", direction: "in", label: "Object API" },
    ],
    maxRps: 10000,
    maxConnections: 5000,
    baseLatencyMs: 15,
    routingStrategy: "none",
    scaling: "managed",
    providers: [
      {
        provider: "S3",
        costPerMonth: 20,
        maxRps: 10000,
        maxConnections: 5000,
        baseLatencyMs: 15,
      },
      {
        provider: "GCS",
        costPerMonth: 18,
        maxRps: 11000,
        maxConnections: 4500,
        baseLatencyMs: 17,
      },
      {
        provider: "Azure Blob",
        costPerMonth: 22,
        maxRps: 12000,
        maxConnections: 6000,
        baseLatencyMs: 14,
      },
      {
        provider: "R2",
        costPerMonth: 10,
        maxRps: 8000,
        maxConnections: 4000,
        baseLatencyMs: 12,
      },
    ],
  },
  {
    type: "search-engine",
    label: "Search Engine",
    name: "Elasticsearch",
    category: "storage",
    description: "Full-text search and analytics engine",
    icon: "Search",
    costPerMonth: 70,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 3500,
    maxConnections: 1000,
    baseLatencyMs: 20,
    routingStrategy: "none",
    queueLimit: 300,
    timeoutMs: 3000,
    scaling: "counter",
    providers: [
      {
        provider: "Elasticsearch",
        costPerMonth: 70,
        maxRps: 3500,
        maxConnections: 1000,
        baseLatencyMs: 20,
      },
      {
        provider: "OpenSearch",
        costPerMonth: 55,
        maxRps: 3000,
        maxConnections: 900,
        baseLatencyMs: 22,
      },
      {
        provider: "Meilisearch",
        costPerMonth: 40,
        maxRps: 2000,
        maxConnections: 500,
        baseLatencyMs: 12,
      },
      {
        provider: "Typesense",
        costPerMonth: 35,
        maxRps: 2500,
        maxConnections: 600,
        baseLatencyMs: 15,
      },
    ],
  },

  {
    type: "time-series-db",
    label: "Time-Series DB",
    name: "InfluxDB",
    category: "storage",
    description: "Optimized for high-rate timestamped writes and range queries",
    icon: "LineChart",
    costPerMonth: 55,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 40000,
    maxConnections: 3000,
    baseLatencyMs: 5,
    routingStrategy: "none",
    queueLimit: 2000,
    timeoutMs: 4000,
    scalesReadsOnly: true,
    scaling: "counter",
    // Tradeoff axes: cost, write throughput, latency
    //   Influx           — balanced default
    //   VictoriaMetrics  — best write throughput, lowest latency, premium
    //   TimescaleDB      — SQL-compatible, slower
    //   Prometheus       — cheapest, low throughput
    providers: [
      {
        provider: "InfluxDB",
        costPerMonth: 55,
        maxRps: 40000,
        maxConnections: 3000,
        baseLatencyMs: 5,
      },
      {
        provider: "VictoriaMetrics",
        costPerMonth: 65,
        maxRps: 70000,
        maxConnections: 4000,
        baseLatencyMs: 3,
      },
      {
        provider: "TimescaleDB",
        costPerMonth: 70,
        maxRps: 30000,
        maxConnections: 2000,
        baseLatencyMs: 8,
      },
      {
        provider: "Prometheus",
        costPerMonth: 40,
        maxRps: 20000,
        maxConnections: 1500,
        baseLatencyMs: 8,
      },
    ],
  },

  // --- Messaging ---
  {
    type: "message-queue",
    label: "Message Queue",
    name: "RabbitMQ",
    category: "messaging",
    description: "Message broker for async communication between services",
    icon: "MailPlus",
    costPerMonth: 30,
    ports: [
      { id: "amqp-in-0", protocol: "AMQP", direction: "in" },
      { id: "amqp-out-0", protocol: "AMQP", direction: "out" },
    ],
    maxRps: 10000,
    maxConnections: 5000,
    baseLatencyMs: 4,
    routingStrategy: "broadcast",
    queueLimit: 50000,
    scaling: "counter",
    providers: [
      {
        provider: "RabbitMQ",
        costPerMonth: 30,
        maxRps: 10000,
        maxConnections: 5000,
        baseLatencyMs: 4,
      },
      {
        provider: "SQS",
        costPerMonth: 20,
        maxRps: 5000,
        maxConnections: 3000,
        baseLatencyMs: 10,
      },
      {
        provider: "Kafka",
        costPerMonth: 60,
        maxRps: 50000,
        maxConnections: 20000,
        baseLatencyMs: 3,
      },
      {
        provider: "NATS",
        costPerMonth: 30,
        maxRps: 15000,
        maxConnections: 8000,
        baseLatencyMs: 1,
      },
    ],
  },
  {
    type: "stream-processor",
    label: "Stream Processor",
    name: "Kafka Streams",
    category: "compute",
    description: "Windowed aggregation and transformation over event streams",
    icon: "Waves",
    costPerMonth: 60,
    ports: [
      { id: "amqp-in-0", protocol: "AMQP", direction: "in" },
      { id: "sql-out-0", protocol: "SQL", direction: "out" },
    ],
    maxRps: 30000,
    maxConnections: 5000,
    baseLatencyMs: 5,
    routingStrategy: "passthrough",
    queueLimit: 5000,
    timeoutMs: 8000,
    scaling: "counter",
    // Tradeoff axes: cost, throughput, latency
    //   Kafka Streams — balanced default
    //   Flink         — highest throughput, premium price
    //   Spark         — cheap-ish but slow (micro-batch)
    //   Kinesis       — cheapest managed, capped throughput
    providers: [
      {
        provider: "Kafka Streams",
        costPerMonth: 60,
        maxRps: 30000,
        maxConnections: 5000,
        baseLatencyMs: 5,
      },
      {
        provider: "Flink",
        costPerMonth: 85,
        maxRps: 60000,
        maxConnections: 8000,
        baseLatencyMs: 4,
      },
      {
        provider: "Spark Streaming",
        costPerMonth: 65,
        maxRps: 25000,
        maxConnections: 4000,
        baseLatencyMs: 12,
      },
      {
        provider: "Kinesis",
        costPerMonth: 45,
        maxRps: 18000,
        maxConnections: 3000,
        baseLatencyMs: 8,
      },
    ],
  },
  {
    type: "worker",
    label: "Worker",
    name: "Celery",
    category: "compute",
    description: "Consumes async jobs from a message queue",
    icon: "Cog",
    costPerMonth: 25,
    ports: [
      { id: "amqp-in-0", protocol: "AMQP", direction: "in" },
      { id: "sql-out-0", protocol: "SQL", direction: "out" },
      { id: "s3-out-0", protocol: "S3", direction: "out" },
    ],
    maxRps: 1500,
    maxConnections: 2000,
    baseLatencyMs: 35,
    routingStrategy: "none",
    queueLimit: 100,
    timeoutMs: 10000,
    scaling: "counter",
    providers: [
      {
        provider: "Celery",
        costPerMonth: 25,
        maxRps: 1500,
        maxConnections: 2000,
        baseLatencyMs: 35,
      },
      {
        provider: "BullMQ",
        costPerMonth: 28,
        maxRps: 2500,
        maxConnections: 4000,
        baseLatencyMs: 30,
      },
      {
        provider: "Sidekiq",
        costPerMonth: 40,
        maxRps: 3500,
        maxConnections: 6000,
        baseLatencyMs: 20,
      },
      {
        provider: "Lambda",
        costPerMonth: 15,
        maxRps: 5000,
        maxConnections: 10000,
        baseLatencyMs: 100,
      },
    ],
  },
];

export function getBlocksByCategory(): Record<
  BlockCategory,
  BlockDefinition[]
> {
  const grouped: Record<BlockCategory, BlockDefinition[]> = {
    networking: [],
    compute: [],
    storage: [],
    messaging: [],
    security: [],
  };

  for (const block of BLOCK_DEFINITIONS) {
    grouped[block.category].push(block);
  }

  return grouped;
}

export function getBlockDefinition(type: string): BlockDefinition | undefined {
  return BLOCK_DEFINITIONS.find((b) => b.type === type);
}

export const PROTOCOL_COLORS: Record<string, string> = {
  HTTP: "#3b82f6",
  TCP: "#6b7280",
  SQL: "#8b5cf6",
  Redis: "#ef4444",
  AMQP: "#f97316",
  S3: "#22c55e",
  DNS: "#06b6d4",
};
