import type { BlockCategory, BlockDefinition } from "./types";

// Special start block — not shown in palette, auto-placed per level
export const TRAFFIC_SOURCE_BLOCK: BlockDefinition = {
  type: "traffic-source",
  label: "Users",
  name: "Traffic",
  category: "networking",
  description: "Incoming user traffic — the entry point for all requests",
  icon: "Users",
  costPerMonth: 0,
  ports: [
    { id: "http-out-0", protocol: "HTTP", direction: "out" },
  ],
  maxRps: Infinity,
  maxConnections: Infinity,
  baseLatencyMs: 0,
  routingStrategy: "passthrough",
};

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  // --- Networking ---
  {
    type: "dns",
    label: "DNS",
    name: "Route 53",
    category: "networking",
    description: "Domain name resolution — entry point for all traffic",
    icon: "Globe",
    costPerMonth: 5,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 50000,
    maxConnections: 100000,
    baseLatencyMs: 1,
    routingStrategy: "passthrough",
    latencyCurve: "flat",
    providers: [
      { provider: "Route 53", costPerMonth: 5, maxRps: 50000, maxConnections: 100000, baseLatencyMs: 1 },
      { provider: "Cloudflare DNS", costPerMonth: 0, maxRps: 100000, maxConnections: 200000, baseLatencyMs: 1 },
      { provider: "Cloud DNS", costPerMonth: 4, maxRps: 40000, maxConnections: 80000, baseLatencyMs: 2 },
      { provider: "Azure DNS", costPerMonth: 6, maxRps: 60000, maxConnections: 120000, baseLatencyMs: 1 },
    ],
  },
  {
    type: "cdn",
    label: "CDN",
    name: "CloudFront",
    category: "networking",
    description: "Content delivery network — caches static assets at edge",
    icon: "Zap",
    costPerMonth: 50,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 100000,
    maxConnections: 200000,
    baseLatencyMs: 5,
    routingStrategy: "passthrough",
    latencyCurve: "flat",
    hitRate: 0.85,
    providers: [
      { provider: "CloudFront", costPerMonth: 50, maxRps: 100000, maxConnections: 200000, baseLatencyMs: 5 },
      { provider: "Cloud CDN", costPerMonth: 45, maxRps: 80000, maxConnections: 160000, baseLatencyMs: 6 },
      { provider: "Azure CDN", costPerMonth: 55, maxRps: 110000, maxConnections: 220000, baseLatencyMs: 4 },
      { provider: "Cloudflare", costPerMonth: 20, maxRps: 150000, maxConnections: 300000, baseLatencyMs: 3 },
    ],
  },
  {
    type: "load-balancer",
    label: "Load Balancer",
    name: "Nginx",
    category: "networking",
    description: "Distributes traffic across multiple servers",
    icon: "GitBranch",
    costPerMonth: 25,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out", label: "Server 1" },
      { id: "http-out-1", protocol: "HTTP", direction: "out", label: "Server 2" },
      { id: "http-out-2", protocol: "HTTP", direction: "out", label: "Server 3" },
    ],
    maxRps: 50000,
    maxConnections: 100000,
    baseLatencyMs: 1,
    routingStrategy: "round-robin",
    latencyCurve: "flat",
    providers: [
      { provider: "Nginx", costPerMonth: 25, maxRps: 50000, maxConnections: 100000, baseLatencyMs: 1 },
      { provider: "HAProxy", costPerMonth: 20, maxRps: 60000, maxConnections: 120000, baseLatencyMs: 1 },
      { provider: "AWS ALB", costPerMonth: 35, maxRps: 80000, maxConnections: 200000, baseLatencyMs: 2 },
      { provider: "Traefik", costPerMonth: 15, maxRps: 30000, maxConnections: 60000, baseLatencyMs: 2 },
    ],
  },
  {
    type: "api-gateway",
    label: "API Gateway",
    name: "Kong",
    category: "networking",
    description: "API management, routing, and throttling",
    icon: "Route",
    costPerMonth: 40,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 20000,
    maxConnections: 50000,
    baseLatencyMs: 5,
    routingStrategy: "passthrough",
    latencyCurve: "flat",
    queueLimit: 500,
    providers: [
      { provider: "Kong", costPerMonth: 40, maxRps: 20000, maxConnections: 50000, baseLatencyMs: 5 },
      { provider: "AWS API GW", costPerMonth: 50, maxRps: 30000, maxConnections: 80000, baseLatencyMs: 8 },
      { provider: "Apigee", costPerMonth: 60, maxRps: 25000, maxConnections: 60000, baseLatencyMs: 6 },
    ],
  },

  // --- Security ---
  {
    type: "firewall",
    label: "Firewall",
    name: "AWS WAF",
    category: "security",
    description: "Filters malicious traffic and enforces security rules",
    icon: "Shield",
    costPerMonth: 20,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 50000,
    maxConnections: 100000,
    baseLatencyMs: 2,
    routingStrategy: "passthrough",
    latencyCurve: "flat",
    providers: [
      { provider: "AWS WAF", costPerMonth: 20, maxRps: 50000, maxConnections: 100000, baseLatencyMs: 2 },
      { provider: "Cloudflare WAF", costPerMonth: 15, maxRps: 60000, maxConnections: 120000, baseLatencyMs: 1 },
      { provider: "Azure Firewall", costPerMonth: 30, maxRps: 70000, maxConnections: 140000, baseLatencyMs: 2 },
    ],
  },
  {
    type: "rate-limiter",
    label: "Rate Limiter",
    name: "Rate Limiter",
    category: "security",
    description: "Throttles excessive requests to prevent abuse",
    icon: "Gauge",
    costPerMonth: 15,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out" },
    ],
    maxRps: 30000,
    maxConnections: 60000,
    baseLatencyMs: 3,
    routingStrategy: "passthrough",
    latencyCurve: "flat",
  },

  // --- Compute ---
  {
    type: "app-server",
    label: "App Server",
    name: "Node.js",
    category: "compute",
    description: "Runs application logic and business rules",
    icon: "Cpu",
    costPerMonth: 50,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "tcp-in-0", protocol: "TCP", direction: "in" },
      { id: "sql-out-0", protocol: "SQL", direction: "out" },
      { id: "redis-out-0", protocol: "Redis", direction: "out" },
      { id: "amqp-out-0", protocol: "AMQP", direction: "out" },
      { id: "s3-out-0", protocol: "S3", direction: "out" },
    ],
    maxRps: 3000,
    maxConnections: 6000,
    baseLatencyMs: 12,
    routingStrategy: "passthrough",
    queueLimit: 200,
    timeoutMs: 2000,
    providers: [
      { provider: "Node.js", costPerMonth: 35, maxRps: 3000, maxConnections: 6000, baseLatencyMs: 12 },
      { provider: "Go", costPerMonth: 55, maxRps: 8000, maxConnections: 16000, baseLatencyMs: 5 },
      { provider: "Java/Spring", costPerMonth: 45, maxRps: 5000, maxConnections: 10000, baseLatencyMs: 15 },
      { provider: "Python/Django", costPerMonth: 30, maxRps: 2000, maxConnections: 4000, baseLatencyMs: 20 },
    ],
  },
  {
    type: "auto-scaler",
    label: "Auto Scaler",
    name: "AWS ASG",
    category: "compute",
    description: "Dynamically distributes load across scaled instances",
    icon: "Scaling",
    costPerMonth: 10,
    ports: [
      { id: "http-in-0", protocol: "HTTP", direction: "in" },
      { id: "http-out-0", protocol: "HTTP", direction: "out", label: "Instance 1" },
      { id: "http-out-1", protocol: "HTTP", direction: "out", label: "Instance 2" },
      { id: "http-out-2", protocol: "HTTP", direction: "out", label: "Instance 3" },
    ],
    maxRps: 100000,
    maxConnections: 200000,
    baseLatencyMs: 0,
    routingStrategy: "round-robin",
    providers: [
      { provider: "AWS ASG", costPerMonth: 10, maxRps: 100000, maxConnections: 200000, baseLatencyMs: 0 },
      { provider: "K8s HPA", costPerMonth: 8, maxRps: 100000, maxConnections: 200000, baseLatencyMs: 0 },
      { provider: "GCP MIG", costPerMonth: 12, maxRps: 100000, maxConnections: 200000, baseLatencyMs: 0 },
    ],
  },

  // --- Storage ---
  {
    type: "sql-db",
    label: "SQL Database",
    name: "PostgreSQL",
    category: "storage",
    description: "Relational database for structured data",
    icon: "Database",
    costPerMonth: 80,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 2000,
    maxConnections: 500,
    baseLatencyMs: 20,
    routingStrategy: "none",
    latencyCurve: "cubic",
    queueLimit: 500,
    timeoutMs: 5000,
    providers: [
      { provider: "PostgreSQL", costPerMonth: 80, maxRps: 2000, maxConnections: 500, baseLatencyMs: 20 },
      { provider: "MySQL", costPerMonth: 70, maxRps: 2500, maxConnections: 600, baseLatencyMs: 18 },
      { provider: "Aurora", costPerMonth: 120, maxRps: 5000, maxConnections: 1000, baseLatencyMs: 10 },
      { provider: "Cloud SQL", costPerMonth: 90, maxRps: 3000, maxConnections: 700, baseLatencyMs: 15 },
    ],
  },
  {
    type: "nosql-db",
    label: "NoSQL Database",
    name: "MongoDB",
    category: "storage",
    description: "Document database for flexible schemas",
    icon: "Layers",
    costPerMonth: 60,
    ports: [{ id: "sql-in-0", protocol: "SQL", direction: "in" }],
    maxRps: 5000,
    maxConnections: 2000,
    baseLatencyMs: 10,
    routingStrategy: "none",
    queueLimit: 1000,
    timeoutMs: 3000,
    providers: [
      { provider: "MongoDB", costPerMonth: 60, maxRps: 5000, maxConnections: 2000, baseLatencyMs: 10 },
      { provider: "DynamoDB", costPerMonth: 50, maxRps: 10000, maxConnections: 5000, baseLatencyMs: 5 },
      { provider: "Cassandra", costPerMonth: 70, maxRps: 15000, maxConnections: 3000, baseLatencyMs: 8 },
      { provider: "Firestore", costPerMonth: 40, maxRps: 3000, maxConnections: 1000, baseLatencyMs: 15 },
    ],
  },
  {
    type: "cache",
    label: "Cache",
    name: "Redis",
    category: "storage",
    description: "In-memory cache for ultra-fast reads",
    icon: "MemoryStick",
    costPerMonth: 40,
    ports: [{ id: "redis-in-0", protocol: "Redis", direction: "in" }],
    maxRps: 30000,
    maxConnections: 10000,
    baseLatencyMs: 1,
    routingStrategy: "none",
    latencyCurve: "flat",
    hitRate: 0.80,
    providers: [
      { provider: "Redis", costPerMonth: 40, maxRps: 30000, maxConnections: 10000, baseLatencyMs: 1 },
      { provider: "Memcached", costPerMonth: 30, maxRps: 50000, maxConnections: 15000, baseLatencyMs: 1 },
      { provider: "ElastiCache", costPerMonth: 55, maxRps: 40000, maxConnections: 12000, baseLatencyMs: 1 },
      { provider: "Dragonfly", costPerMonth: 35, maxRps: 60000, maxConnections: 20000, baseLatencyMs: 1 },
    ],
  },
  {
    type: "object-storage",
    label: "Object Storage",
    name: "S3",
    category: "storage",
    description: "Scalable object storage for files and media",
    icon: "HardDrive",
    costPerMonth: 20,
    ports: [{ id: "s3-in-0", protocol: "S3", direction: "in" }],
    maxRps: 10000,
    maxConnections: 5000,
    baseLatencyMs: 15,
    routingStrategy: "none",
    providers: [
      { provider: "S3", costPerMonth: 20, maxRps: 10000, maxConnections: 5000, baseLatencyMs: 15 },
      { provider: "GCS", costPerMonth: 18, maxRps: 9000, maxConnections: 4500, baseLatencyMs: 16 },
      { provider: "Azure Blob", costPerMonth: 22, maxRps: 12000, maxConnections: 6000, baseLatencyMs: 14 },
      { provider: "R2", costPerMonth: 10, maxRps: 8000, maxConnections: 4000, baseLatencyMs: 12 },
    ],
  },
  {
    type: "search-engine",
    label: "Search Engine",
    name: "Elasticsearch",
    category: "storage",
    description: "Full-text search and analytics engine",
    icon: "Search",
    costPerMonth: 70,
    ports: [{ id: "tcp-in-0", protocol: "TCP", direction: "in" }],
    maxRps: 3000,
    maxConnections: 1000,
    baseLatencyMs: 25,
    routingStrategy: "none",
    latencyCurve: "cubic",
    queueLimit: 300,
    timeoutMs: 3000,
    providers: [
      { provider: "Elasticsearch", costPerMonth: 70, maxRps: 3000, maxConnections: 1000, baseLatencyMs: 25 },
      { provider: "OpenSearch", costPerMonth: 60, maxRps: 2800, maxConnections: 900, baseLatencyMs: 28 },
      { provider: "Meilisearch", costPerMonth: 40, maxRps: 2000, maxConnections: 500, baseLatencyMs: 15 },
      { provider: "Typesense", costPerMonth: 35, maxRps: 2500, maxConnections: 600, baseLatencyMs: 12 },
    ],
  },

  // --- Messaging ---
  {
    type: "message-queue",
    label: "Message Queue",
    name: "RabbitMQ",
    category: "messaging",
    description: "Message broker for async communication between services",
    icon: "MailPlus",
    costPerMonth: 35,
    ports: [
      { id: "amqp-in-0", protocol: "AMQP", direction: "in" },
      { id: "amqp-out-0", protocol: "AMQP", direction: "out" },
    ],
    maxRps: 10000,
    maxConnections: 5000,
    baseLatencyMs: 5,
    routingStrategy: "broadcast",
    latencyCurve: "flat",
    queueLimit: 50000,
    providers: [
      { provider: "RabbitMQ", costPerMonth: 35, maxRps: 10000, maxConnections: 5000, baseLatencyMs: 5 },
      { provider: "SQS", costPerMonth: 25, maxRps: 5000, maxConnections: 3000, baseLatencyMs: 10 },
      { provider: "Kafka", costPerMonth: 60, maxRps: 50000, maxConnections: 20000, baseLatencyMs: 2 },
      { provider: "NATS", costPerMonth: 20, maxRps: 30000, maxConnections: 10000, baseLatencyMs: 1 },
    ],
  },
  {
    type: "worker",
    label: "Worker",
    name: "Celery",
    category: "compute",
    description: "Consumes async jobs from a message queue",
    icon: "Cog",
    costPerMonth: 30,
    ports: [
      { id: "amqp-in-0", protocol: "AMQP", direction: "in" },
      { id: "sql-out-0", protocol: "SQL", direction: "out" },
      { id: "s3-out-0", protocol: "S3", direction: "out" },
    ],
    maxRps: 1000,
    maxConnections: 2000,
    baseLatencyMs: 50,
    routingStrategy: "none",
    queueLimit: 100,
    timeoutMs: 10000,
    providers: [
      { provider: "Celery", costPerMonth: 30, maxRps: 1000, maxConnections: 2000, baseLatencyMs: 50 },
      { provider: "BullMQ", costPerMonth: 25, maxRps: 2000, maxConnections: 4000, baseLatencyMs: 30 },
      { provider: "Sidekiq", costPerMonth: 35, maxRps: 3000, maxConnections: 6000, baseLatencyMs: 20 },
      { provider: "Lambda", costPerMonth: 15, maxRps: 5000, maxConnections: 10000, baseLatencyMs: 100 },
    ],
  },
];

export function getBlocksByCategory(): Record<BlockCategory, BlockDefinition[]> {
  const grouped: Record<BlockCategory, BlockDefinition[]> = {
    networking: [],
    compute: [],
    storage: [],
    messaging: [],
    security: [],
  };

  for (const block of BLOCK_DEFINITIONS) {
    grouped[block.category].push(block);
  }

  return grouped;
}

export function getBlockDefinition(type: string): BlockDefinition | undefined {
  return BLOCK_DEFINITIONS.find((b) => b.type === type);
}

export const PROTOCOL_COLORS: Record<string, string> = {
  HTTP: "#3b82f6",
  TCP: "#6b7280",
  SQL: "#8b5cf6",
  Redis: "#ef4444",
  AMQP: "#f97316",
  S3: "#22c55e",
  DNS: "#06b6d4",
};
